# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains



class TestText():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_text(self):
        self.driver.get(
            "http://127.0.0.1:5500/__%D8%A7%D8%B6%D8%A7%D9%81%D8%A9%20%D9%85%D9%83%D8%A7%D8%AA%D8%A8%D8%A9%20%D8%AC%D8%AF%D9%8A%D8%AF%D8%A9__%20(2).html")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Cmb_SenderCode").click()
        dropdown = self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Cmb_SenderCode")
        dropdown.find_element(By.XPATH, "//option[. = 'إدارة المدعى العام العسكرى']").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").send_keys("sdf")
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocCode").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocCode").send_keys("adf")
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocNumber").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocNumber").send_keys("fasd")
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_SenderBranch").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_SenderBranch").send_keys("fad")
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").click()
        element = self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").send_keys("1/2/2222")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(3)").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_Txt_DocDate").send_keys("1/2/2022")
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(2)").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_GridView1_ctl05_chk_Resp").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(2)").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_GridView1_ctl05_chk_Involved").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_GridView1_ctl04_chk_Involved").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_TxT_Subject").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_TxT_Subject").send_keys("adfadfadfadf")
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_FileUpload1").click()
        self.driver.find_element(By.ID, "ctl00_ContentPlaceHolder1_FileUpload1").send_keys(
            "C:\\Users\\Hady Ahmed\\Downloads\\حجز.pdf")
